spacetelescope/pysiaf

.travis.yml, pysiaf/__init__.py, pysiaf/aperture.py, pysiaf/constants.py, pysiaf/iando/read.py, pysiaf/siaf.py, pysiaf/utils/polynomial.py
This PR makes syntax adjustments to enable `pysiaf` to run on Python 2.7 as well as 3.x.  No changes in algorithms.  Unit tests pass on both 2.7 and 3.6. 
Motivation: While most/all new code should definitely be in Python 3, at least for right now WebbPSF still supports Python 2.7. in particular this is needed because much of the Pandeia ETC has not yet been fully ported to Py3.  So making `pysiaf` work on Python 2 is necessary before it can be used in WebbPSF instead of `jwxml` .  
Assuming you approve @Johannes-Sahlmann, I'd really appreciate if this could be merged in ASAP. @shanosborne has some updates to WebbPSF that rely on `pysiaf` and we're trying to get a new WebbPSF release out next week...
=> Add Python 2.7 compatibility along with 3.x

MANIFEST.in, setup.py
The `RELIC-INFO` file needs to be packaged with the `sdist` tarball in order for relic to do its job (outside of a Git repository setting). This PR should take care of the problem. I suggest generating a new tag based on these modifications and push another tarball up to PyPi.
Resolves #17
=> Fix RELIC implementation

pysiaf/utils/compare.py, pysiaf/utils/rotations.py, pysiaf/utils/tools.py
Adding `from future` imports to a few files that I missed before, to further ensure everything works fine on both 2.7 and 3+. Thanks to @jhunkeler for noticing that I had missed a couple spots before.
=> more py27 compatibility - add 'from future' imports to additional files

pysiaf/__init__.py, pysiaf/aperture.py, pysiaf/tests/test_aperture.py, pysiaf/tests/test_projection.py, pysiaf/utils/projection.py
Adds options to aperture.idl_to_tel and aperture tel_to_idl that allow the use of more accurate prescriptions that do not rely on the planar approximation.
This PR also introduces the projection tools which implement tangent-plane de-/projection.
=> Accurate idl to tel

pysiaf/aperture.py, pysiaf/siaf.py, pysiaf/tests/test_projection.py
These plotting updates come from problems found while investigating issues #1 and #71.
A summary of the changes made:
- Made NIRSpec MSA detector channel plotting possible by plotting the channels from the NRS_FULL apertures
- Removed `NotImplementedError` for `siaf.py` `plot_detector_channels() `
- Add ax argument to `aperture.py` and `siaf.py` `plot_detector_channels()`
- Renamed `plot_all_apertures()` `showchannels` argument to `detector_channels` in order to match `plot_main_apertures()`
- Updated labeling arguments to be more logical between the `siaf.py` and `aperture.py` `plot()` methods
- Updated `siaf.py plot()` docstring to have frame examples in lowercase since that's what the argument expects.
=> Plotting updates

setup.py
In the `setup.py` file, the package_data list is pointing to `prd_data/HST/*/*.dat`. However, there are 2 problems with this line. 
1. Not all of the files in the HST directory end in `.dat`, and thus this line leaves those files out
2. This line contains an extra sub-directory. IE the file path should be  `prd_data/HST/*`, since this is where the files live and there is no extra directory beneath this anymore (I see that you put in a PR about this earlier today). 
I found this problem when I was running `Travis` for `WebbPSF`, and it failed because it couldn’t find the HST files (particualrly `amu.rep-Latest` which isn't a `.dat` file) and was failing. As a heads up, this is to some extent blocking our 0.8 release of WebbPSF.
=> Package_data pointing in setup.py for HST data

setup.py
The Astroconda package for pysiaf will not build for python 3.7 with the dependency `openpyxl` pinned to version `2.5.0`. This relaxes that constraint so the dependencies can be solved for the build.
=> Relax openpyxl version req to allow building conda package for python 3.7

pysiaf/__init__.py
Need to update the code in `__init__.py` to sort through the online PRD versions in the same way that it does in `constants.py` - aka in a way that takes into account the new PRD naming structure.
=> Update print out in __init__ for new PRD numbering

docs/pysiaf/index.rst, pysiaf/aperture.py, pysiaf/siaf.py, pysiaf/tests/test_aperture.py
Following up our conversation in slack - this PR adds transformations to/from the `sky` coordinate system. The actual transforms are implemented via calls to the `rotations.sky_to_tel` and `tel_to_sky` transforms, wrapped into similarly named methods on the `Aperture` class. 
PR should be pretty self-explanatory, hopefully. I included some basic documentation and a unit test too.
=> implement transforms to/from sky coordinates

pysiaf/aperture.py
A small followup to PR #177: The `transform` keyword argument added to the `aperture.plot` function should also be passed through to the call to `ax.fill`. This makes the `fill=True` option work when a transform is set.
=> in aperture.plot, pass transform keyword through to fill 

.github/workflows/publish-to-pypi.yml
Adding a command to the PublishtoPyPi CI action to handle new git security update here: https://github.community/t/environment-variable-github-workspace-unusuable-when-setting-environment-variables/17266
=> Fix git security issue affecting CI

.github/workflows/publish-to-pypi.yml
Add workflow dispatch to allow for manual triggering of publishtopypi CI
=> Allow use to trigger CI workflow

.github/workflows/publish-to-pypi.yml
This is a fix for https://jira.stsci.edu/browse/SPB-959, and additionally needs to wait for https://github.com/spacetelescope/action-publish_to_pypi/pull/20 to merge before it can be merged.
This pull request as well as the above referenced one were tested successfully in this action run: https://github.com/zanecodes/pysiaf/actions/runs/2314790714 (the failure to publish at the end is because my fork is intentionally not set up with the PyPI token to publish for real)
=> Update to use action-publish_to_pypi reusable workflow, which should fix git security issue

pysiaf/tests/test_aperture.py
Patch to try and resolve issues described in Issue #186 .
Added a custom FGS aperture threshold of 0.26 to test_jwst_aperture_transforms. Anything smaller caused an error.
Commented out the sky_to_det(det_to_sky) transform check
All generate scripts now run without errors, and all pytest tests pass.
=> Fgs aperture threshold / sky_to_det(det_to_sky) 

pysiaf/__init__.py
This allows wrapper scripts to more easily manage what is output
from their execution.
=> Change prd version printing to logging

pysiaf/__init__.py
Fixes #300. Presumably due to some github functionality change (?), the regex needed to be updated to not include as many paths of the subdirectory name. 
Before: 
```
In [1]: import pysiaf
**WARNING**: LOCAL JWST PRD VERSION PRDOPSSOC-062 CANNOT BE CHECKED AGAINST ONLINE VERSION
```
After:
```
In [1]: import pysiaf
```
=> fix URL regex for online PRD checking

.github/workflows/ci.yml, pyproject.toml
use `pip install .[test]` @mfixstsci
=> fix `pip install` in CI

.readthedocs.yaml, MANIFEST.in, README.md, docs/conf.py, docs/pysiaf/index.rst, docs/pysiaf/polynomial.rst, docs/pysiaf/projection.rst, docs/pysiaf/rotations.rst, docs/pysiaf/tools.rst, pyproject.toml, pysiaf/aperture.py, pysiaf/iando/write.py, pysiaf/siaf.py, pysiaf/utils/compare.py, pysiaf/utils/polynomial.py, pysiaf/utils/tools.py
* Adding pyproject.toml
* Adding MANIFEST.in
Addresses #313, #307
=> Repo Clean Up (Additions)

pysiaf/aperture.py
This PR adds logic around the `ax.fill` plotting command in `aperture.py` to avoid the transform in Hubble apertures. Either there is a difference in the way the siaf files are handled by the code base OR the default value for the `transform` kwarg in `ax.fill` is needed for the HST apertures to plot correctly.
=> HST Aperture Hotfix

generate/generate_nircam.py
In efforts to shrink the size of the the pysiaf package, we are removing older versions of the siaf. @Witchblade101 found lines in `generate_nircam.py` that can compare newly generated siaf files to specific versions. After discussions with @mgennaro we believe this code block was used at one time compare to a benchmark siaf release.
This PR removes those lines, I was able to run `generate_nircam.py` afterwards with no problem.
=> WIP: Remove Comparison Lines in `generate_nircam.py`

pysiaf/siaf.py
This PR updates the `plot_main_apertures` function to add a new parameter `mission`, which allows choosing to plot the JWST, HST, or Roman SIAF apertures. 
```
pysiaf.siaf.plot_main_apertures(mission='JWST')
pysiaf.siaf.plot_main_apertures(mission='HST', fill=False)
pysiaf.siaf.plot_main_apertures(mission='Roman')
```
(Minor note, I don't know why for HST it defaults to filling the apertures, but for JWST and Roman it does not. In fact the plot function seems incapable of filling those apertures, regardless of whether plot=True or plot=False is set. Also, COS is not included for HST because the plot function can't handle circular apertures currently. Fixing either of those issues is out of scope for this PR however).
=> extend plot_main_apertures to also plot HST or Roman apertures

pysiaf/__init__.py
`pkg_resources` was deprecated way back in `python 3.10` for removal in `python 3.12`. Since this package is using dynamic versioning from  `setuptools_scm` it should be loading its version from the `setuptools_scm` generated file not via `pkg_resources`.
This PR removes the use of `pkg_resources` and instead loads version information from the file generated by `setuptools_scm` as part of package install.
=> Remove usage of `pkg_resources`

pysiaf/iando/read.py, pysiaf/tests/test_polynomial.py, pysiaf/utils/polynomial.py
This PR fixes a few deprecation warnings: 
1. Replaces the deprecated `importlib.resources.path` method with the new `files()` API 
2. Drops the `1` in `numpy.random.rand(1)`, and calls `squeeze` to resolve a similar issue where length-one vectors are being made where the result is expected to be scalar, since numpy 1.25:
```
DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, 
and will error in future. Ensure you extract a single element from your array 
before performing this operation. (Deprecated NumPy 1.25.)
```
Closes https://github.com/spacetelescope/pysiaf/issues/360
=> Fix deprecation warnings from importlib and numpy

pysiaf/siaf.py
Made find_apernames() case-insensitive as described in issue #367
=> Made find_apernames() case-insensitive

pysiaf/siaf.py, pysiaf/tests/test_aperture.py, pysiaf/tests/test_plotting.py
The existing `plot_main_apertures` function has useful lists defining the main apertures per observatory. This PR refactors the code to pull the definition of those lists out into a separate `get_main_apertures` function. This allows accessing and using the list of main apertures in other contexts outside of just the `plot_main_apertures` function. 
Example usage: 
```
In [2]: import pysiaf
In [3]: im_aps, spec_aps, coron_aps = pysiaf.siaf.get_main_apertures('jwst')
In [4]: im_aps
Out[4]:
[<pysiaf.Aperture object AperName=NRCA5_FULL >,
<pysiaf.Aperture object AperName=NRCB5_FULL >,
<pysiaf.Aperture object AperName=NIS_CEN >,
<pysiaf.Aperture object AperName=MIRIM_ILLUM >,
<pysiaf.Aperture object AperName=FGS1_FULL >,
<pysiaf.Aperture object AperName=FGS2_FULL >,
<pysiaf.Aperture object …
```
=> refactor part of plot_main_apertures to get_main_apertures
